---
- hosts: all
  become: yes
  tasks: 
  - name: iwant to install tree
    apt:
      name: tree
      state: present
  - name: i want to install wget
    apt:
      name: wget
      state: present
  - name: i want to instll webserver
    apt: 
      name: apache2
      state: present
